language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "pip install isodate mako hgapi GitPython pytest mock pytz mercurial pep8"
  - "apt-get install git"
# command to run tests
script: make
