language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install isodate mako hgapi GitPython pytest mock pytz mercurial pep8 rednose"
  - "sudo apt-get install git-core"
  - "sudo chmod 777 /tmp"
# command to run tests
script: make
